AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Guardfile'
    - 'Rakefile'
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Rails/ActionFilter:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
SignalException:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'
Style/PredicateName:
  Exclude:
    - 'app/serializers/**/*'
