development: &defaults
  allowed_email_domains:
  app_domain: 'props.dev'
  domain_name: 'gapps-domain-name'
  extra_domains: 'some-domain.org'
  emails:
    default_from: 'props@example.com'
  newrelic_license_key: 'newrelic_license_key'
  omniauth_provider_key: 'omniauth-key'
  omniauth_provider_secret: 'omniauth-secret'
  auth0_api_client_id: 'auth0_api_client_id'
  auth0_api_client_secret: 'auth0_api_client_secret'
  auth0_api_audience: 'auth0_api_audience'
  auth0_domain: 'auth0_domain'
  rollbar_access_token: 'rollbar_token'
  secret_key_base: 'please-change-me'
  sendgrid_password: 'sendgrid_password'
  sendgrid_user_name: 'sendgrid_user_name'
  skylight_token: 'skylight-token'
  slack:
    default_channel: 'default_channel'
    token: 'slack_token'

test:
  <<: *defaults

production:
  <<: *defaults
  app_domain: <%= ENV['APP_DOMAIN'] %>
  domain_name: <%= ENV['GAPPS_DOMAIN_NAME'] %>
  extra_domains: <%= ENV['EXTRA_DOMAINS'] %>
  emails:
    default_from: <%= ENV['EMAILS_DEFAULT_FROM'] %>
  omniauth_provider_key: <%= ENV['OMNIAUTH_KEY'] %>
  omniauth_provider_secret: <%= ENV['OMNIAUTH_SECRET'] %>
  auth0_api_client_id: <%= ENV['AUTH0_API_CLIENT_ID'] %>
  auth0_api_client_secret: <%= ENV['AUTH0_API_CLIENT_SECRET'] %>
  auth0_api_audience: <%= ENV['AUTH0_API_AUDIENCE'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sendgrid_user_name: <%= ENV['SENDGRID_USER_NAME'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  slack:
    default_channel: <%= ENV['SLACK_DEFAULT_CHANNEL'] %>
    token: <%= ENV['SLACK_TOKEN'] %>
