defaults: &defaults
  app_domain: '<%= ENV["APP_DOMAIN"] || "props.dev" %>'
  single_domain_mode: '<%= ENV["SINGLE_DOMAIN_MODE"] %>'
  emails:
    default_from: '<%= ENV["EMAIL_DEFAULT_FROM"] || "props@example.com" %>'
  slack:
    default_channel: '#general'

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
